fix: remove deprecated js.commonjs-core-modules-replacements option for GraalVM 25.1
The option was removed in GraalVM 25.1.x and causes all JS plugins to fail with:
  IllegalArgumentException: Could not find option with name js.commonjs-core-modules-replacements